name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

# ==================== 关键：KV 永久绑定 ====================
kv_namespaces = [
  { binding = "KV", id = "daeec53920c4aab95f6d608b5eeb2e0" }
]
